name: Backend CI

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: edumind
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: docker build -t edumind-backend ./backend

      - name: Run backend container
        run: |
          docker run -d --name test-backend --network host -e DB_HOST=localhost -e DB_USER=postgres -e DB_PASS=postgres edumind-backend
          sleep 5

      - name: Test backend endpoint
        run: |
          curl --fail http://localhost:3000 || exit 1
